"""UCC - Unitary Compiler Collection.

A multi-level AOT compiler and Schrodinger Virtual Machine for quantum circuits
(Clifford + T and beyond).
"""

from ucc._ucc_core import (
    AstNode,
    BytecodePass,
    BytecodePassManager,
    Circuit,
    ExpandRotPass,
    ExpandTPass,
    GateType,
    HeisenbergOp,
    HirModule,
    HirPass,
    HirPassManager,
    Instruction,
    MultiGatePass,
    NoiseBlockPass,
    Opcode,
    OpType,
    ParseError,
    PeepholeFusionPass,
    Program,
    RemoveNoisePass,
    SingleAxisFusionPass,
    State,
    StatevectorSqueezePass,
    SwapMeasPass,
    Target,
    compile,
    compute_reference_syndrome,
    default_bytecode_pass_manager,
    default_hir_pass_manager,
    execute,
    get_statevector,
    lower,
    max_sim_qubits,
    parse,
    parse_file,
    sample,
    sample_k,
    sample_k_survivors,
    sample_survivors,
    svm_backend,
    trace,
    version,
)

__all__ = [
    "AstNode",
    "BytecodePass",
    "BytecodePassManager",
    "Circuit",
    "ExpandRotPass",
    "ExpandTPass",
    "GateType",
    "HeisenbergOp",
    "HirModule",
    "Instruction",
    "MultiGatePass",
    "NoiseBlockPass",
    "Opcode",
    "OpType",
    "ParseError",
    "HirPass",
    "HirPassManager",
    "PeepholeFusionPass",
    "Program",
    "RemoveNoisePass",
    "SingleAxisFusionPass",
    "State",
    "StatevectorSqueezePass",
    "SwapMeasPass",
    "Target",
    "compile",
    "compute_reference_syndrome",
    "default_bytecode_pass_manager",
    "default_hir_pass_manager",
    "execute",
    "get_statevector",
    "lower",
    "max_sim_qubits",
    "parse",
    "parse_file",
    "sample",
    "sample_k",
    "sample_k_survivors",
    "sample_survivors",
    "svm_backend",
    "trace",
    "version",
]

__version__ = version()
