#!/usr/bin/env bash
# Set up background S3 sync for UCC results.
#
# Installs a systemd timer that syncs the results/ directory to S3
# every 5 minutes. Runs at lowest I/O priority (ionice) so it never
# competes with the sampling workload.
#
# Usage:
#   bash paper/magic/setup_s3_sync.sh <s3-bucket-name>
#
# Example:
#   bash paper/magic/setup_s3_sync.sh ucc-soft-results
#
# Prerequisites:
#   - AWS CLI installed and configured (or IAM instance profile attached)
#   - S3 bucket exists: aws s3 mb s3://<bucket-name>

set -euo pipefail

BUCKET="${1:?Usage: setup_s3_sync.sh <s3-bucket-name>}"
REPO_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
RESULTS_DIR="$REPO_DIR/results"
INSTANCE_ID=$(hostname)
S3_PREFIX="s3://$BUCKET/$INSTANCE_ID"

echo "=== S3 Sync Setup ==="
echo "Results dir: $RESULTS_DIR"
echo "S3 target:   $S3_PREFIX"
echo

# Verify AWS access
if ! aws sts get-caller-identity &>/dev/null; then
    echo "ERROR: AWS credentials not configured."
    echo "Attach an IAM instance profile or run 'aws configure'."
    exit 1
fi
echo "AWS identity: $(aws sts get-caller-identity --query Arn --output text)"

# Verify bucket access
if ! aws s3 ls "s3://$BUCKET" &>/dev/null; then
    echo "ERROR: Cannot access s3://$BUCKET"
    echo "Create it: aws s3 mb s3://$BUCKET"
    exit 1
fi

# Create the sync script
SYNC_SCRIPT="/usr/local/bin/ucc-s3-sync.sh"
sudo tee "$SYNC_SCRIPT" > /dev/null <<EOF
#!/bin/bash
# Auto-generated by setup_s3_sync.sh
# Syncs UCC results to S3 at lowest I/O priority
ionice -c3 aws s3 sync "$RESULTS_DIR/" "$S3_PREFIX/" \
    --exclude "*" --include "*.csv" --include "*.log" \
    --quiet 2>/dev/null || true
EOF
sudo chmod +x "$SYNC_SCRIPT"

# Create systemd service
sudo tee /etc/systemd/system/ucc-s3-sync.service > /dev/null <<EOF
[Unit]
Description=Sync UCC results to S3

[Service]
Type=oneshot
ExecStart=$SYNC_SCRIPT
User=$(whoami)
Nice=19
IOSchedulingClass=idle
EOF

# Create systemd timer (every 5 minutes)
sudo tee /etc/systemd/system/ucc-s3-sync.timer > /dev/null <<EOF
[Unit]
Description=Periodic S3 sync for UCC results

[Timer]
OnBootSec=2min
OnUnitActiveSec=5min
AccuracySec=30s

[Install]
WantedBy=timers.target
EOF

# Enable and start
sudo systemctl daemon-reload
sudo systemctl enable --now ucc-s3-sync.timer

echo
echo "=== S3 sync active ==="
echo "Timer: systemctl status ucc-s3-sync.timer"
echo "Manual sync: sudo systemctl start ucc-s3-sync.service"
echo "View logs: journalctl -u ucc-s3-sync.service"
echo "Syncs every 5 minutes at idle I/O priority."

# Do an initial sync
echo
echo "--- Running initial sync ---"
sudo systemctl start ucc-s3-sync.service
echo "Done. Check: aws s3 ls $S3_PREFIX/"
